apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: app
  annotations:
    azure.workload.identity/client-id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
automountServiceAccountToken: false
